### ISSUE TITLE
Alpha channel rendering broken for raw images on linux

### ISSUE THREAD

**Issue by ao2** [IENT/YUView#404] opened 2021-08-06 08:46 UTC
Hi,

As mentioned in https://github.com/IENT/YUView/issues/369#issuecomment-860568937 and subsequent comments rendering the alpha channel of **raw images** does not work on linux, while it works for PNG images.
I tried with either the `QT_QPA_PLATFORM=xcb` or `QT_QPA_PLATFORM=wayland` and rendering is broken in both cases even though in different ways.
* In the `xcb` case I think the issue is that `functionsGui::pixmapImageFormat()` always returns `QImage::Format_RGB32` and so the alpha is ignored at render time.
* In the `wayland` case `functionsGui::pixmapImageFormat()` returns `QImage::Format_ARGB32_Premultiplied` as expected but the view is buggy (translucent areas are corrupted, glitches all round in them when moving the window), maybe because blitting in the viewport is not performed correctly (can this be a QT bug?). 

A workaround that I found is to force `functionsGui::pixmapImageFormat()` to return `QImage::Format_ARGB32` but I am not sure if I like this solution.

Thanks, Antonio

**Comment by ao2** [comment] 2021-08-09 10:27
Attaching some files to make it easier to reproduce:
[YUView_raw_rgba_alpha_channel_samples.zip](https://github.com/IENT/YUView/files/6953693/YUView_raw_rgba_alpha_channel_samples.zip)

To pick up the correct RGB formats for the raw files, select "Custom" from the drop down and uncheck "Planar".

The blue part should be fully transparent, but it isn't on linux.

**Comment by ChristianFeldmann** [comment] 2021-08-18 09:17
Thank you for the report. When I will have time I will take a look.

**Comment by ChristianFeldmann** [comment] 2021-09-21 13:03
So I was able to reproduce the problem and as you suspected it is the image format that is returned from the function `pixmapImageFormat` that causes the problem because it has no alpha component in some cases. The idea of this function was to return the native format for the platform to speed up rendering. But this will not perform alpha blending if we need alpha. I think the solution is:
 - Return the native format if we don't need alpha
 - Return `Format_ARGB32` otherwise

**Comment by ChristianFeldmann** [comment] 2021-10-29 07:14
Sorry for the long delay but I finally merged a fix (as described above). The same thing was also present under macOS. So looks like nobody tested files with alpha on Mac either 😆 
Closing for now. Please check if it works now (on develop) and re-open if it is not yet fixed. 
Thank you!

**Closed as completed by ChristianFeldmann** 2021-10-29 07:14 UTC
Labels: bug, affects:Linux

**Comment by ao2** [comment] 2021-10-29 07:18
Thank you @ChristianFeldmann I'll try to test it next week and confirm that everything is OK.
Ciao, Antonio
