### ISSUE TITLE
[Regression] NN is always BT.709 limited for all matrices choices, normal in Bilinear

### ISSUE THREAD

**Issue by ValZapod** [IENT/YUView#431] opened 2021-11-05 08:50 UTC
On windows I use sample from https://github.com/IENT/YUView/files/7379120/RAWINPUT8BITYUV.zip: 

![image](https://user-images.githubusercontent.com/31514790/140483707-dc4e3a86-e775-4039-b635-5708dd133ecb.png)
![image](https://user-images.githubusercontent.com/31514790/140483724-b06843f7-603b-495b-80d7-fdd654cbd7ea.png)

**Comment by ValZapod** [comment] 2021-11-05 08:54
This is a regression since latest stable release 2.11.1, their matrix choice works even on NN.

**Comment by ChristianFeldmann** [comment] 2021-11-07 17:24
I don't understand your message. Could you please provide a clean description of what the problem is? Can you not select the chroma interpolation mode? Do you think the output of the interpolation is wrong? What is the problem?

**Comment by ValZapod** [comment] 2021-11-07 17:37
On nearest neigbour all matrices look the same as in BT.709 limited, while on two others they are different, and it is a regression since stable. As for whether interpolation is correct, it does not matter. (Though I dunno what chroma sample location you are using (only left, I suppose?) and whether you are using at least Lancoz 2, as specified in ITU-T Series H Supplement 18, but again that does not affect the matrix color changes.)

**Comment by ChristianFeldmann** [comment] 2021-11-08 08:41
Ok. So when `Nearest Neighbour` is selected as interpolation mode then the chroma conversion does not seem to influence the display anymore. This is probably something in the conversion functions. I reworked and improved them quite a bit. Will check.

**Comment by ValZapod** [comment] 2021-11-08 11:44
> chroma conversion

Chroma and luma conversion. You are supposed to first upsample to 4:4:4 and then apply the matrix to R'G'B'. Of course other ideas are possible and you are supposed to clamp the Y'CbCr in Y'CbCr, not in R'G'B' or in case of xvYCC you are not clamping at all, for example, Y'CbCr BT.709 values 139, 151, 24 is RGB -21, 182, 181.

**Comment by ChristianFeldmann** [comment] 2021-11-08 19:04
Thanks for the report. Issue is fixed in develop. You were also right that this was a regression which was introduced by my refactoring of the YUV conversion functions. Unfortunately I don't have enough time to add enough testing here so that this could have been caught.

**Closed by ChristianFeldmann** 2021-11-08 19:04 UTC
Labels: bug

**Comment by ValZapod** [comment] 2021-11-09 08:21
Fixed indeed!
