### ISSUE TITLE
Bitrate Plot for AV1

### ISSUE THREAD

**Issue by ghost** [IENT/YUView#434] opened 2021-11-24 08:31 UTC
Hi,

Just wondering if this might be issue on my side, but I do not see bitrate plot for AV1 encoded clips. Does YUView support displaying plots for AV1 video clips?

Running YUView 2.12 on Arch Linux.

**Comment by ChristianFeldmann** [comment] 2021-11-24 08:42
Hi!
It definitely should support it. So this is a bug. Thanks for the report!

**Comment by ghost** [comment] 2021-11-24 09:09
@ChristianFeldmann feel free to poke me if/when you have prelimenary fix, I can rebuild on my side and verify if it works.

**Comment by ChristianFeldmann** [comment] 2021-11-24 09:19
Thank you will do. I just encoded an AV1 stream and I can confirm this. Since AV1 is always wrapped into a webm container which we open with ffmpeg (libavformat) the bug must be somewhere in there.

**Comment by ChristianFeldmann** [comment] 2021-11-25 12:30
Fix was merged into develop. 
Please reopen if you find anything missing.

**Closed as completed by ChristianFeldmann** 2021-11-25 12:30 UTC
Labels: bug

**Comment by ghost** [comment] 2021-11-26 06:40
Verified from develop branch commit 586bec28, AV1 plots work.
