### ISSUE TITLE
ubuntu16.04 compile failed

### ISSUE THREAD

**Issue by ZhouJieYeah** [IENT/YUView#235] opened 2020-05-21 10:50 UTC
when I compile the project followling in the instruction, compile failed for the QT chart module. Then I installed the QT chart form source, compile again and got a Q_NAMESPACE not defined error.

**Comment by ChristianFeldmann** [comment] 2020-05-21 21:26
Hi. Sorry but I can not really say what went wrong here for you. Do you compile Qt yourself? Because this is not really necessary for Ubuntu. There should be precompiled binaries for these. We also use these in our CI pipeline for building. E.g. take a look at 
 - https://github.com/IENT/YUView/blob/master/deployment/codeshipBuildContainerUbuntu.sh
or at
 - https://github.com/IENT/YUView/blob/master/.travis.yml
to see how YUView is built in CI on ubuntu 16.04

**Comment by ChristianFeldmann** [comment] 2020-06-01 21:33
I will close this issue for now as I can't reproduce it. For us compilation on Ubuntu 16.04 works just fine. Please let me know if you encounter more problems.

**Closed by ChristianFeldmann** 2020-06-01 21:33 UTC
