### ISSUE TITLE
Preserve zoom/position for each open file

### ISSUE THREAD

**Issue by SnapCracklePork** [IENT/YUView#156] opened 2018-11-01 21:42 UTC
When switching from one file to another the zoom and position of the current file is applied.  It would be nice to have an option to 'sync' the zoom/position of all the open files...or not.

**Comment by ChristianFeldmann** [comment] 2018-11-03 09:58
ok so what should be the intended behavior? should yuview remember the position/zoom per item or should the view be reset every time? 
resetting the view is easy using ctrl+0

**Comment by SnapCracklePork** [comment] 2018-11-03 23:18
I would like the zoom for each item to be be remembered. Perhaps with a option to switch between this and the current operation.

**Comment by nolyn** [comment] 2018-11-05 09:00
I think an option would be fine. I regularly use the current behavior to
look for bugs or artifacts in different versions of the same YUV.

**Comment by ChristianFeldmann** [comment] 2018-11-08 16:21
@SnapCracklePork if possible please test the implementation in the branch feature/position_zomm_per_item

**Comment by SnapCracklePork** [comment] 2018-11-08 21:30
Do you have a windows installer available?  I am not a user of Qt.  I
started installing it but it is a bit of a monster!

Darrin

**Comment by ChristianFeldmann** [comment] 2018-11-08 21:33
For windows you are in luck. Appveyor builds every commit we make and packs an installer and a zip file which you can download [here](https://ci.appveyor.com/project/aachenmax/yuview/builds/20148819/artifacts).

**Comment by SnapCracklePork** [comment] 2018-11-08 21:50
Found the option in settings.  Works great.  It may be more useful to put
the option box in the 'display options' window.

Darrin

**Comment by ChristianFeldmann** [comment] 2018-11-12 16:39
I added saving/loading in the playlist and merged it to develop

**Closed by ChristianFeldmann** 2018-11-12 16:39 UTC
Labels: enhancement

**Comment by SnapCracklePork** [comment] 2018-11-14 01:11
Many thanks.
