### ISSUE TITLE
"Wrong" color interpolation at hard edges?

### ISSUE THREAD

**Issue by HarHarLinks** [IENT/YUView#396] opened 2021-07-19 16:35 UTC
![image](https://user-images.githubusercontent.com/2803622/126194863-6e4cd99f-13d6-44b3-b55a-824c4dd69368.png)
I'm debugging this data, where parts of the image are irrelevant (0 valued here).
Visually one might believe that there is a weird border artifact when in fact the displayed color is inconsistent.
I tried messing with the Chroma Interpolation setting and also YUV format (chroma position), but the former has no setting applicable for my case and the latter does not seem to let me select/save anything but the 0 and 1/2 offsets.

**Comment by ChristianFeldmann** [comment] 2021-07-19 21:41
There seem to be multiple issues packed into one here. Let me try to understand this:
 - So you think the current interpolation of the chroma component (or essentially the YUV to RGB conversion) is doing something wrong? Could you detail further what is wrong here? For performance reasons we are not applying a chroma interpolation by default.
 - What exactly is the intended behavior that you are looking for?

**Comment by HarHarLinks** [comment] 2021-07-19 22:13
The GUI says you're applying NN interpolation by default? ;P
I am looking for the dark green areas in the above image to have the same color as the medium green areas. The same applies for the light green areas. Both indicated by the red markings below. The artifacts at the bottom borders that look like shadow is what we see from closeup in the above picture.

![image](https://user-images.githubusercontent.com/2803622/126233448-70d31cb3-6b08-4061-a277-cd700a060f46.png)

In the following image we also see a border. By looking at the YUV values we can see that these should be much closer to the grey-ish part of the non-empty image and not have this green tint.

![image](https://user-images.githubusercontent.com/2803622/126233635-486d3a0f-de3b-44bb-8be0-e13357079a96.png)

It looks to me like some vertical interpolation issue to me.

The behaviour I'm looking for: I am synthesizing only certain blocks of a frame, the rest is zero as a default value as I don't need them down the line. I use YUView for visual debugging and comparison with an original. These light/dark green parts look like artifacts of something being wrong in my program, when the actual values shown when zooming in are as expected. I hope that's more clear?

**Comment by ChristianFeldmann** [comment] 2021-07-20 08:15
Aah yes in these screenshots it des not look correct. The nearest neighbor interpolation is just "no interpolation". I think for nearest neighbor I just apply the chroma values to all 4 pixel values without any interpolation. But I will have to double check this. Could you send a sample file? That would help a lot.

**Comment by HarHarLinks** [comment] 2021-07-20 13:58
Please find the file from which I took the screenshots here: https://rwth-aachen.sciebo.de/s/A9qVi6TuqopfNOT

**Comment by ChristianFeldmann** [comment] 2021-07-21 21:49
Ok so I looked into the code a bit and it seems like the interpolation mode is not really take into account here but we are always performing "correct" interpolation depending on the chroma location of the pixels. For YUV 4:2:0 8 bit this is different. This should definitely be aligned with how it behaves for 10 bit content.

**Comment by ChristianFeldmann** [comment] 2021-07-26 20:23
Hi. I have merged a fix for this. Basically I disabled the chroma position interpolation for the nearest neighbor interpolation mode. Now the same U/V values will be assumed for all 4 pixel conversions (in case of YUV 4:2:0).

**Closed as completed by ChristianFeldmann** 2021-07-26 20:23 UTC
Labels: bug

**Comment by HarHarLinks** [comment] 2021-07-27 10:36
Looks good, at least in my test case! :) Thank you
![image](https://user-images.githubusercontent.com/2803622/127140346-fa3aa3c7-1b55-4b1f-8e40-856456af4cd6.png)
