### ISSUE TITLE
Not working for 8k contents

### ISSUE THREAD

**Issue by Edwardfpan** [IENT/YUView#198] opened 2019-12-04 21:28 UTC
It seems that this tool can only work until 4k.

I have problem displaying 8k contents, such as 7680x4320, or 8192x4608, 8b or 10b.

Also, I would like to see it can display FP16 or other HDR formats.

Thanks!

**Comment by ChristianFeldmann** [comment] 2019-12-05 07:52
Hi! 
There is no specific limitation on the size of the image. Beside the higher memory consumption any format should work. I successfully used YUView with 8k content. Could you provide more information on what you tried to open? Even better would be a file for me to reproduce the error with. 

HDR formats with higher bit-depths are supported in a way. We can read higher bit-depth files and you can inpect all the values. But for displaying the image on screen we map the values to RGB 8 bit for rendering. So there is no real HDR output of the HDR images. Since YUView is based on Qt we are limited by the capabilities here.

**Comment by ChristianFeldmann** [comment] 2019-12-27 11:51
Hi I just had a little bit of time and tested 8k and 16k content and I could see no issue with it. I am closing this issue for now. Please provide more information or a file which fails so I can verify this issue.

**Closed by ChristianFeldmann** 2019-12-27 11:51 UTC
