### ISSUE TITLE
Videos getting out of sync 

### ISSUE THREAD

**Issue by dpasqualin** [IENT/YUView#289] opened 2020-11-09 07:27 UTC
I'm trying to compare two encoded files watching them side by side, but at some point the video on the left sort of jumps back a few frames and the playback gets out of sync. I tried hevc (with ffmpeg and libde265) and h264, and the problem happens even when comparing the file with itself.

I'm using the master from github compiled on Linux (Ubuntu 20), but I also tried with the version from Flatpak, same issue.

**Comment by ChristianFeldmann** [comment] 2020-11-11 13:23
Hi. 
I have observed something similar. I think the issue is with how we do seeking using libavformat. The seeking does not seem to be doing exactly what I am expecting. For that we definitely need some fixes. 
Some suggestions for workaround if you really need this:
 - If you decode both files to YUV first. That should definitely be in sync.
 - You could try to put the videos in raw annexB streams (`ffmpeg -i video.mp4 -c:v copy -f h264 video.h264` or h265). YUView reads raw annexB streams natively and the seeking should work correctly here.

**Comment by dpasqualin** [comment] 2020-11-15 12:59
Thank you for your answer @ChristianFeldmann , however the command that worked for me was this one (from [ffmpeg documentation](https://ffmpeg.org/ffmpeg-bitstream-filters.html#toc-h264_005fmp4toannexb)): `ffmpeg -i video.mp4 -codec copy -bsf:v h264_mp4toannexb video.ts`

Again, amazing tool, thank you. I hope you don't mind if I make an unrelated question here, but in the bitstream analysis menu I can only see part of the data. There is a message in the bottom saying "partial parsing done. enable full parsing if needed", but I couldn't find where to enable the full parsing.

**Comment by ChristianFeldmann** [comment] 2020-11-15 13:28
Ah and then for the ts file it did not go out of sync anymore? That is interesting as ts is also just a container. But maybe seeking just works much better in that container ...

Yes that is currently a bit hidden. On the `Bitstream Analysis` -> `Packet Analysis` Tab there is a checkbock named `Parse Entire Bitstream`. This definitely needs a better handling in the UI.

**Comment by dpasqualin** [comment] 2020-11-17 13:34
The ts file played alright, but I think the `h264_mp4toannexb` did the trick, not the container. I changed the command to `ffmpeg -i video.mp4 -codec copy -bsf:v h264_mp4toannexb video.mp4` and it worked as well.

Thank you for the tip on `Parse Entire Bitstream`, worked like a charm.

**Comment by ChristianFeldmann** [comment] 2020-11-17 13:59
Ah good to know. Then I will close this issue for now. But some improvement to the seeking is definitely still needed.

**Closed as completed by ChristianFeldmann** 2020-11-17 13:59 UTC
