### ISSUE TITLE
gbrp10le file crash + RGB Big Endian not supported

### ISSUE THREAD

**Issue by ValZapod** [IENT/YUView#409] opened 2021-09-11 12:33 UTC
[rawle.zip](https://github.com/IENT/YUView/files/7147809/rawle.zip)
Size unpacked is 99 532 800 bytes.

While ffplay.exe -video_size 3840x2160 -pixel_format gbrp10le C:\Users\ZAQU\rawle.rgb works.

Please note that white there indeed is not 100% white, but 1020 out of 1023.

I will also note that I do not understand how to force gbrp10be, is big endian even supported, a setting like with GBR, 10 bit, planar stuff? [rawrgbbe.zip](https://github.com/IENT/YUView/files/7147829/rawrgbbe.zip)

On a very similar file it does not crash but may crash when start typing 3840, but usually works (nice thing the hex editor).
[rawrgble.zip](https://github.com/IENT/YUView/files/7147822/rawrgble.zip)

99 532 800 bytes too.

As I said I checked latest develop branch artifact and stable.

**Comment by ValZapod** [comment] 2021-09-11 12:37
Please tell me if you cannot reproduce I will try to do a backtrace.

Please note that ffmpeg integration is really broken since the use of removed API.

**Comment by ChristianFeldmann** [comment] 2021-09-13 08:16
Hi. Thanks for the report. I will try to reproduce the crash and see if I can make this work or if this is a missing feature. 
What exactly do you mean with: "...ffmpeg integration is really broken since the use of removed API." Do you mean ffmpeg in YUView? What exactly is not working for you? Please open another issue if you are having problems there.

**Comment by ChristianFeldmann** [comment] 2021-09-21 10:47
I found one slight problem with RGB with alpha which caused a segmentation fault and fixed it. So you can try again if you can still see a crash. 
For the rest I don't quite understand your question. E.g. 
```
I will also note that I do not understand how to force gbrp10be, is big endian even supported, a setting like with GBR, 10 bit, planar stuff?
```
I don't understand what you mean. What are you trying to force? Are you not able to display the rgb file you provided correctly? I can see the file correctly in YUView.

**Comment by ValZapod** [comment] 2021-09-21 11:01
Perfect, fixed!!

> crash but may crash when start typing 3840

This is still not fixed!! Type into 3989 x 2160, it will crash! ;)

> Are you not able to display the rgb file you provided correctly

No, **be** file is supposed to be the same as in **le**. This is big endian and little endian, in this case I suppose byte, not bit endianness.

> see the file correctly in YUView

Yeah, sure it does open.

**Comment by ChristianFeldmann** [comment] 2021-09-24 09:18
I think now I understand what you mean. So there are two things. One is that big endian for RGB is not supported. I hear you. That is a feature request and I started on that one. 

However, I am not able to reproduce the crash that you mentioned. Could you please:
 - give precise instructions how to reproduce it? I mean really precise.
 - What version are you using to get the crash? Are you on develop or are you using a release version?

**Comment by ValZapod** [comment] 2021-09-24 14:00
> * Are you on develop

I am on latest artifact of develop.

So, as I said initial crash on open is fixed. Now as for 2nd crash:

Open same file in rawle.zip on latest develop HEAD.
Put 2160. Then put 3989 (I just did a typo, it is supposed to be 3840).
It will crash.

**Comment by ChristianFeldmann** [comment] 2021-11-01 17:24
So it took a bit of more time but here it is. I just merged a bigger refactoring for the RGB support (including support for big endian). Alongside the patch for RGB + alpha + linux this should now all work. 
Please check this out and test it. For the crash that you reported: I was still not able to reproduce that. Neither with the old version now with the current develop one. If you still see it, please describe the exact steps to reproduce it (i.e. click here, type XYZ, click here, ...)

**Comment by ValZapod** [comment] 2021-11-05 05:01
It now just crashes all the time.

**Closed** 2021-11-05 08:54 UTC
Labels: bug, enhancement
