### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by jonno85uk** [IENT/YUView#382] opened 2021-06-25 19:33 UTC
I have cloned the latest commit 4ae46b7

With the latest qt-creator installer, I have installed up to date qt libraries and build tools.

After opening YUView.pro in qt-creator and configured the project I have tried to build the project. After compiling a large portion of the project it fails with the following error

```
del libYUViewLib.a 2>NUL
ar -rc libYUViewLib.a @object_script.YUViewLib 
mingw32-make[1]: Leaving directory 'C:/Users/jon/Documents/code/YUView/YUViewLib'
cd YUViewApp\ && ( if not exist Makefile C:\Qt\6.1.1\mingw81_64\bin\qmake.exe -o Makefile C:\Users\jon\Documents\code\YUView\YUViewApp\YUViewApp.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:/Qt/Tools/mingw810_64/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'C:/Users/jon/Documents/code/YUView/YUViewApp'
mingw32-make[1]: Leaving directory 'C:/Users/jon/Documents/code/YUView/YUViewApp'
mingw32-make[1]: *** No rule to make target 'C:/Users/jon/Documents/code/YUView/YUViewLib/YUViewLib.lib', needed by 'YUView.exe'.  Stop.
mingw32-make: *** [Makefile:76: sub-YUViewApp-make_first] Error 2
20:14:40: The process "C:\Qt\Tools\mingw810_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project YUView (kit: Desktop Qt 6.1.1 MinGW 64-bit)
When executing step "Make"
```

**Comment by jonno85uk** [comment] 2021-06-25 19:35
![buildyuview](https://user-images.githubusercontent.com/14606456/123476582-d065c880-d5f4-11eb-8af2-9388881c8bfd.PNG)

**Comment by ChristianFeldmann** [comment] 2021-06-28 08:07
Let me try with the latest Qt version. Maybe something changed there. The other cause may be MinGW. We never tested the build using minGW. On Windows we are using the msvc builds.

**Comment by ChristianFeldmann** [comment] 2021-06-28 12:16
So I tried with Qt Version 6.1.2 and msvc and it works nicely. So probably the problem is with MinGW. As I said we never tested building with minGW. Although there should not be a big difference with it. 
Could you try a clean re-build? Also could you post the exact commands you used to check out YUView and build it? Did you do an out-of-tree build as described in the wiki page?

**Comment by ChristianFeldmann** [comment] 2021-06-29 11:43
So I could recreate this issue with the latest minGW (8.1) and Qt 6.1.1.

**Comment by ChristianFeldmann** [comment] 2021-07-06 08:54
I found some stuff that was not working as intended for the minGW build. This is fixed now. Please try the current develop version again.

**Closed as completed by ChristianFeldmann** 2021-07-06 08:54 UTC
Labels: bug, affects:Windows

**Comment by jonno85uk** [comment] 2021-07-07 18:50
@ChristianFeldmann  Thanks. It's building now.

**Comment by Freed-Wu** [comment] 2022-05-15 16:41
It looks like this program can be built by mingw-w64? So package this program to <https://github.com/msys2/MINGW-packages> is possible, really?

**Comment by Freed-Wu** [comment] 2022-05-16 02:40
Perhaps I met the similar problem:

```
make[1]: Leaving directory '/mnt/c/Users/wzy/Desktop/MINGW-packages/mingw-w64-yuview/src/build/YUViewLib'
cd YUViewApp/ && ( test -e Makefile || C:/msys64/mingw64/bin/qmake.exe -o Makefile C:/Users/wzy/Desktop/MINGW-packages/mingw-w64-yuview/src/YUView/YUViewApp/YUViewApp.pro -spec win32-g++ ) && make -f Makefile
Project MESSAGE: MinGW Compiler detected.
WARNING: Failure to find: WindowsAppIcon_res.o
make[1]: Entering directory '/mnt/c/Users/wzy/Desktop/MINGW-packages/mingw-w64-yuview/src/build/YUViewApp'
make[1]: *** No rule to make target 'C:/Users/wzy/Desktop/MINGW-packages/mingw-w64-yuview/src/build/YUViewLib/YUViewLib.lib', needed by 'YUView.exe'.  Stop.
make[1]: Leaving directory '/mnt/c/Users/wzy/Desktop/MINGW-packages/mingw-w64-yuview/src/build/YUViewApp'
make: *** [Makefile:76: sub-YUViewApp-make_first] Error 2
```
