### ISSUE TITLE
Qt6 debug build failure

### ISSUE THREAD

**Issue by 1div0** [IENT/YUView#516] opened 2023-02-20 12:20 UTC
**Compilation failure w/ Qt6**

**To Reproduce**
€ qmake6 -spec linux-clang ../../YUView.pro CONFIG+=debug

**Version (please complete the following information):**
 - OS: F37
 - Version develop
 - If you compiled YUView yourself then which Qt version did you use?
€ rpm -qi qt6-qtbase
Name        : qt6-qtbase
Version     : 6.4.2
Release     : 4.fc37
Architecture: x86_64
Install Date: Po 13. február 2023, 08:31:04
Group       : Unspecified
Size        : 11613026
License     : LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
Signature   : RSA/SHA256, Št  9. február 2023, 09:49:43, Key ID f55ad3fb5323552a
Source RPM  : qt6-qtbase-6.4.2-4.fc37.src.rpm
Build Date  : St  8. február 2023, 14:33:37
Build Host  : buildvm-x86-16.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://qt-project.org/
Bug URL     : https://bugz.fedoraproject.org/qt6-qtbase
Summary     : Qt6 - QtBase components
Description :
Qt is a software toolkit for developing applications.

This package contains base tools, like string, xml, and network
handling.

In file included from /2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/ui/ViewStateHandler.cpp:33:
/2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/ui/ViewStateHandler.h:51:33: error: base class has incomplete type
class ViewStateHandler : public QObject
                         ~~~~~~~^~~~~~~
/usr/include/qt6/QtCore/qscopedpointer.h:65:7: note: forward declaration of 'QObject'
class QObject;
      ^
In file included from /2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/ui/ViewStateHandler.cpp:33:
In file included from /2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/ui/ViewStateHandler.h:36:
In file included from /usr/include/qt6/QtCore/QPointer:1:
/usr/include/qt6/QtCore/qpointer.h:38:17: error: static_cast from 'ViewStateHandler *' to 'QPointer<ViewStateHandler>::QObjectType *' (aka 'QObject *'), which are not related by inheritance, is not allowed
    { wp.assign(static_cast<QObjectType*>(p)); return *this; }
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/ui/widgets/PlaylistTreeWidget.h:82:70: note: in instantiation of member function 'QPointer<ViewStateHandler>::operator=' requested here
  void setViewStateHandler(ViewStateHandler *handler) { stateHandler = handler; }
                                                                     ^
2 errors generated.
make[1]: *** [Makefile:3925: src/ui/ViewStateHandler.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/video/videoHandlerYUV.cpp:3446:16: warning: variable 'convOK' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
      else if (yuvFormat.getBitsPerSample() == 10)
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/video/videoHandlerYUV.cpp:3476:10: note: uninitialized use occurs here
  assert(convOK);
         ^~~~~~
/usr/include/assert.h:90:27: note: expanded from macro 'assert'
     (static_cast <bool> (expr)                                         \
                          ^~~~
/2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/video/videoHandlerYUV.cpp:3446:12: note: remove the 'if' if its condition is always true
      else if (yuvFormat.getBitsPerSample() == 10)
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/2TB/usr/src/github.com/1div0/YUView/YUViewLib/src/video/videoHandlerYUV.cpp:3429:14: note: initialize the variable 'convOK' to silence this warning
  bool convOK;
             ^
              = false
1 warning generated.
make[1]: Leaving directory '/2TB/usr/src/github.com/1div0/YUView/Linux/x86-64/YUViewLib'
make: *** [Makefile:48: sub-YUViewLib-make_first] Error 2

**Comment by ChristianFeldmann** [comment] 2023-02-21 09:52
Thx for the report. I could reproduce this in a docker fedora image. Probably something with a newer version of clang. Also happens in release mode.

**Comment by ChristianFeldmann** [comment] 2023-02-21 12:55
Was able to reproduce it on macos12 with clang and Qt6.
Was not able to reproduce on Ubuntu 20 with Qt5 and clang.

**Comment by 1div0** [comment] 2023-02-21 19:29
Checked out the feature/addUpToDateCI branch and compiled OK.

Danke schön.

**Comment by ChristianFeldmann** [comment] 2023-02-21 19:46
Yep I am just looking at some warnings with the new Qt version. I will add the new macOS and Ubuntu version to the CI so that this will keep building also with the newest version.

**Comment by ChristianFeldmann** [comment] 2023-02-22 08:02
PR was merged

**Closed as completed** 2023-02-22 08:02 UTC
Labels: bug

**Comment by ValZapod** [comment] 2023-04-30 17:40
When will QT6 be available for Visual Studio 2022 builds?
