### ISSUE TITLE
Cannot open files directly anymore since update 2.6

### ISSUE THREAD

**Issue by schoolmeister** [IENT/YUView#228] opened 2020-04-19 16:42 UTC
Hi,

I updated YUViewer to 2.6 yesterday. Ever since I have not been able to directly open files anymore (e.g. by double clicking the file) in the viewer. I am able to open a file by first opening the viewer and then choosing or dropping the file into it. But when I try to directly open a video file, the viewer attempts to update, downloads all update files in the directory of the video file and then throws errors that it cannot find those files. To demonstrate I included a small demo below [1].

I tried to revert back to version 2.5, but the moment I open YUViewer it starts downloading 2.6 again. I figured this is because I checked the option for automatic updates and that some configuration files must be lying around somewhere, but I'm unsure where to look for them. The "cancel" button during updates also does not seem to work. It just closes the update widget for a brief moment and reopens it.

[1] https://streamable.com/h4iggk

**Comment by schoolmeister** [comment] 2020-04-19 23:49
Update: I've managed to downgrade to version 2.5 in the meantime by opening the faulty version and disabling the auto-update options. Can't believe I didn't think of that earlier. The downgrade helped and everything's back to normal.

**Comment by ChristianFeldmann** [comment] 2020-04-20 10:36
Hi. Thanks for the detailed error description. That really helps. I will take a look on why this does not work anymore. I am also working on Windows but I am not using the "open with" feature. 

Yes you can just disable all the update checking functionality. Good to hear that this way you can still keep on using YUView.

**Comment by ChristianFeldmann** [comment] 2020-04-20 19:22
I can confirm this bug. It probably has to do with the way files are opend with an application on windows. I will check this logic.

**Comment by ChristianFeldmann** [comment] 2020-04-20 20:53
I found the reason for this behavior. When opening YUView by double clicking a file, the execution directory of YUView is the directory that the opened file is in and not the folder that the YUView executable resides. The automatic updater uses that to load the current version file. So I just have to change the automatic updater to use the folder that the executed YUView.exe executable is in.

**Comment by ChristianFeldmann** [comment] 2020-04-23 21:14
Found and fixed the issue. It was really related to where YUView is executed (pwd) relative to the path to YUView.exe. Just what I don't understand is why this was no problem before. Because I can not trace this coming up from the previous (2.5) version. Maybe something with how we link the openSSL libraries.

**Comment by ChristianFeldmann** [comment] 2020-04-23 22:01
I tested it and it works. So this will be fixed in the next release. Thank you again for the bug report!

**Closed by ChristianFeldmann** 2020-04-23 22:01 UTC
Labels: bug
