### ISSUE TITLE
YUView at version 2.14 parses size info incorrectly from filename. 

### ISSUE THREAD

**Issue by fenyi2016** [IENT/YUView#555] opened 2023-12-29 03:45 UTC
**Describe the bug**
YUView at version 2.14 parses size info incorrectly from filename. 

**To Reproduce**
Give a file named "BasketballDrive_1920x1080_50.yuv". 
1. Drag the file to the playlist of yuview. 

**Expected behavior**
The images show right up at version 2.13, but an error shows at version 2.14. 

**Screenshots**
![7C5A1809-B159-4322-8836-2054B24CD3CB](https://github.com/IENT/YUView/assets/22061290/88d37e90-f7f0-4db6-89f8-fe435ed46ee7)

**Version (please complete the following information):**
 - OS: windows 11 home
 - Version: release v2.14
 - If you compiled YUView yourself then which Qt version did you use? No. I just installed the "YUViewSetup.msi".

**Comment by ChristianFeldmann** [comment] 2024-01-01 11:31
Hi! Thanks for the report. This is a duplicate of https://github.com/IENT/YUView/issues/547 and was already fixed in https://github.com/IENT/YUView/pull/549.

**Closed as completed by ChristianFeldmann** 2024-01-01 11:31 UTC
Labels: bug

**Comment by Freed-Wu** [comment] 2024-12-26 14:32
When to release a new version?
