### ISSUE TITLE
NV21 can't display well

### ISSUE THREAD

**Issue by doyee** [IENT/YUView#92] opened 2017-07-13 11:23 UTC
please see the attachements

The NV21 color display is wrong
![arcsoft_software](https://user-images.githubusercontent.com/2289290/28164106-5ceb6ede-6800-11e7-9f20-03e604a4fa78.jpg)
![yuview nv21](https://user-images.githubusercontent.com/2289290/28164111-61028368-6800-11e7-8ad0-17c819cdf8cc.jpg)
[converted_NV21_2016X1512.nv21.zip](https://github.com/IENT/YUView/files/1144932/converted_NV21_2016X1512.nv21.zip)

**Comment by JensAc** [comment] 2017-07-13 11:52
The problem is quite clear.
YUV 4:2:0 file properties expect the file to be in the following format:
Y samples  , U samples  , V samples.
In case of nv21 the U and V samples are interleaved, which is not handled by the player yet. 
In order to obtain a correct display, you need to deinterleave the u and v samples. 
Of course this could also be added as a new color format in the player.

**Comment by doyee** [comment] 2017-07-13 12:49
@JensAc thanks   YUView have not support semiplanr yet.   when is it ready?

**Comment by ChristianFeldmann** [comment] 2017-07-15 16:40
I never came accross this YUV file so we never added support for this. Sometimes I think people just invented new YUV formats just for the fun of it. Anyways, I added support for this NV21 YUV format. The changes are in the YUV420_NV21 branch. Could you check if everything is ok with these changes? Just compile YUView from the branch YUV420_NV21. If you don't know how to compile YUView I can also send you a compile Mac package. I am especially curious if everything works for sequences with more than one frame (the file you attached only contains one frame). Also another question that I have: Is the official file extension for this YUV format ".nv21" or did you add it? If everything works as expected, we can merge these changes to the master branch and deploy them.

**Comment by doyee** [comment] 2017-07-17 07:23
hi ChristianFeldmann ,
thanks for your response.  ONE: the nv21 file that i uploaded last time is offical format.  TWO: please send me a compile Mac package. 

thanks.

**Comment by doyee** [comment] 2017-07-17 07:23
@ChristianFeldmann my mail:  doyee@qq.com

**Comment by doyee** [comment] 2017-07-19 10:45
@ChristianFeldmann thanks , it work well for nv21 sequence frame.   i think you can merge it to master branch now

here is the test file:
https://pan.baidu.com/s/1hsBYjHE

**Comment by ChristianFeldmann** [comment] 2017-07-27 18:16
Fix was merged to the master branch. Enjoy.

**Closed by ChristianFeldmann** 2017-07-27 18:16 UTC
Labels: enhancement
